language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: nNUQKTPTsbRQKgV1mUQ9jt52w+lNGrQtEpd975K9jQGxWvBNJaHb0eTDbuJCO7+OgG77yKiGQcr9gc7oM4WjFFcLoR2qWxRXsgGuyAIiMU85RRBvHXp7+gv1Qa/ko15MKmJo0ACxizAEiT6SIpwdQpo0AaopQKxg26pNN9S52YK6WtUjbgbIjRbcntFXi2CByO6W5d3rXX2pWgoE+j+Qm2UpA8j09i6pghVUcBb+7ngy8D0PBYnXW3pTKzZiFuhdW93n2VPl553q0FQe9jQyoaC0DYkeT1JOyLCd7uME+mZaCsiue2gdWlY6Vbbitv4ccK0qvUblMPvusDV5LJGz2c8V3L9+uC90x30LO1sX/XXG26nyuN2YrKqdmuJJWVqr3cz6c6Z94yBdcnuReJqo1IOuUetwo1fKnB7G9k3qkhDKc3PPzB5Xz/VlKQTnzS5TrSrzog8wWYQhauU5EO/+Bivyyf7FUc+/+ykSIVS+ysfwZw65wOrNaAW3oPs0kJdouXsdotcWsSt+Xbp6FMkhju92xifdWr99MrXzsMpB/ToNdHgQ3LPp+JrU61ASfcb3ojH8k+SggVI5LnsDKtoBIQy8LyWr6FHAwxDadtjyuBAPul/+emLQiUalzG9Y3/+lmQDWT2piha0W0Fw643F/GdxNrdKqws6/MX70el2VhMY=
  file:
    - "unist-util-source.js"
    - "unist-util-source.min.js"
  on:
    tags: true
    node: '9.0'
